# Generated by Django 5.0.7 on 2024-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('last_name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
    ]
