# Generated by Django 5.0.7 on 2024-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('day_time', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
