# Generated by Django 5.0.7 on 2024-07-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('course_name', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('course_table', models.CharField(max_length=250)),
                ('lesson_number', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=250)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mentor')),
            ],
        ),
    ]
