# Generated by Django 5.0.7 on 2024-07-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, null=True)),
                ('meneger', models.CharField(blank=True, max_length=50, null=True)),
                ('now', models.SmallIntegerField(blank=True, choices=[(1, 'Keladi'), (2, 'Otkaz'), (3, "Oylab ko'radi"), (4, 'Kiyin aloqa')], null=True)),
                ('coming', models.SmallIntegerField(blank=True, choices=[(5, 'Online'), (6, 'Offine')], null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
