# Generated by Django 5.0.7 on 2024-08-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
