# Generated by Django 5.0.7 on 2024-08-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_new_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AddField(
            model_name='new',
            name='file',
            field=models.FileField(default=1, upload_to='media_files/'),
            preserve_default=False,
        ),
    ]
