# Generated by Django 5.0.7 on 2024-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_new_img_new_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='file',
        ),
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
