# Generated by Django 5.0.7 on 2024-08-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_new_file_new_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='text',
            field=models.TextField(),
        ),
    ]
