# Generated by Django 5.0.7 on 2024-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AddField(
            model_name='new',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/%Y-%m-%d'),
            preserve_default=False,
        ),
    ]
