# Generated by Django 5.0.7 on 2024-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_mentor_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
