# Generated by Django 5.0.7 on 2024-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_video_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='account_type',
            field=models.CharField(choices=[('0', 'YouTube'), ('1', 'Video_add')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
