# Generated by Django 5.0.7 on 2024-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_video_account_type_video_video_alter_video_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='account_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'YouTube'), (1, 'Video_add')], null=True),
        ),
    ]
